version: '3.7'

volumes:
   gitlab_data: {}

services:
   gitlab_sync:
      build:
         target: ${APPLICATION_ENV}
         context: ./sync
      container_name: gitlab_sync      
      env_file:
         - .env
      working_dir: /srv/sync
      volumes:
         - ./sync:/srv/sync
         - ./.env:/srv/app/.env
         - /srv/sync/node_modules
      links:
         - gitlab_database
      depends_on:
         - gitlab_database
      restart: always

   gitlab_database:
      build:
         context: ./mongodb
      container_name: gitlab_database
      env_file:
         - .env
      environment:
         - AUTH=yes
         - MONGODB_ADMIN_USER=${DB_ROOT}
         - MONGODB_ADMIN_PASS=${DB_ROOT_PWD}
         - MONGODB_APPLICATION_DATABASE=${DB_NAME}
         - MONGODB_APPLICATION_USER=${DB_USER}
         - MONGODB_APPLICATION_PASS=${DB_USER_PWD}
      volumes:
         - gitlab_data:/data
      ports:
         - 28869:27017
      restart: always

   gitlab_metabase:
      image: metabase/metabase
      container_name: gitlab_metabase
      volumes:
         - ./metabase.db:/metabase.db
      ports:
         - 8080:3000
      links:
         - gitlab_database
      depends_on:
         - gitlab_database

